baseURL = "https://docs.multisafepay.com/"
languageCode = "en-us"
title = "MultiSafepay Docs"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

[outputs]
    home = [ "HTML", "JSON"]
    page = [ "HTML"]

[blackfriday]
hrefTargetBlank = true

#CUSTOM PARAMS
[params]
    search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell"

# Menu config

[[menu.main]]
    name = "Getting started"
    url  = "/getting-started/"
    pre = "fa fa-rocket fa-lg"
    weight = 1

[[menu.main]]
    name = "Create a test account"
    url  = "/getting-started/create-a-test-account"
    parent = "Getting started"
    weight = 2

[[menu.main]]
    name = "Set up your account"
    url  = "/getting-started/set-up-your-account"
    parent = "Getting started"
    weight = 3

[[menu.main]]
    name = "Build your integration"
    url  = "/getting-started/build-your-integration"
    parent = "Getting started"
    weight = 4

[[menu.main]]
    name = "Test your integration"
    url  = "/getting-started/test-your-integration"
    parent = "Getting started"
    weight = 5

[[menu.main]]
    name = "Onboard and go live"
    url  = "/getting-started/go-live"
    parent = "Getting started"
    weight = 6

[[menu.main]]
    name = "Glossary"
    url  = "/getting-started/glossary"
    parent = "Getting started"
    weight = 7

[[menu.main]]
    name = "Account"
    url  = "/account/"
    pre = "fa fa-user-circle fa-lg"
    weight = 10

[[menu.main]]
    name = "Payments"
    url  = "/payments/"
    identifier = "payments"
    pre = "fa fa-credit-card fa-lg"
    weight = 20

[[menu.main]]
    name = "About payments"
    url  = "/payments/about/"
    parent = "payments"
    weight = 210

[[menu.main]]
    name = "Build your integration"
    url  = "/payments/integrations/"
    parent = "payments"
    weight = 220

[[menu.main]]
    name = "Add payment methods"
    url  = "/payments/methods/"
    parent = "payments"
    identifier = "payment-methods"
    weight = 230

[[menu.main]]
    name = "Customize your checkout"
    url  = "/payments/checkout"
    parent = "payments"
    weight = 240

[[menu.main]]
    name = "Boost your integration"
    url  = "/payments/boost"
    parent = "payments"
    weight = 250

[[menu.main]]
    name = "Security and legal"
    url  = "/security-and-legal/"
    pre = "fa fa-lock fa-lg"
    weight = 60

    [[menu.main]]
    name = "Developer tools"
    url  = "/developer/"
    pre = "fa fa-cube fa-lg"
    weight = 70

[[menu.main]]
    name = "API Reference"
    url  = "/api/"
    pre = "fa fa-code fa-lg"
    weight = 80