baseURL = "https://docs.multisafepay.com/"
languageCode = "en-us"
title = "MultiSafepay Docs"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

[outputs]
    home = [ "HTML", "JSON"]
    page = [ "HTML"]

[blackfriday]
hrefTargetBlank = true

#CUSTOM PARAMS
[params]
    search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell"

# Menu config

[[menu.main]]
    name = "Getting started"
    url  = "/guides/getting-started/"
    pre = "fa fa-rocket fa-lg"
    weight = 1

[[menu.main]]
    name = "Integrations"
    url  = "/integrations/"
    identifier = "integrations"
    pre = "fa fa-plug fa-lg"
    weight = 10

[[menu.main]]
    name = "Ecommerce integrations"
    url  = "/integrations/ecommerce-integrations"
    parent = "integrations"
    weight = 10

[[menu.main]]
    name = "PWA"
    url  = "/integrations/pwa"
    parent = "integrations"
    weight = 10

[[menu.main]]
    name = "Wrappers and SDKs"
    url  = "/integrations/wrappers"
    parent = "integrations"
    weight = 40

[[menu.main]]
    name = "Cash register software"
    url  = "/integrations/cash-register-software"
    parent = "integrations"
    weight = 60

[[menu.main]]
    name = "Payment Components"
    url  = "/integrations/payment-components"
    parent = "integrations"
    weight = 45

[[menu.main]]
    name = "Community"
    url  = "/integrations/community"
    parent = "integrations"
    weight = 50

[[menu.main]]
    name = "Credit and subscription management"
    url  = "/integrations/credit-and-subscription-management"
    parent = "integrations"
    weight = 50

[[menu.main]]
    name = "Reservation management"
    url  = "/integrations/reservation-management/"
    parent = "integrations"
    weight = 50

[[menu.main]]
    name = "FAQs"
    url  = "/faq/"
    pre = "fa fa-question-circle-o fa-lg"
    weight = 30

[[menu.main]]
    name = "Payment methods"
    url  = "/payment-methods/"
    pre = "fa fa-credit-card fa-lg"
    weight = 40

[[menu.main]]
    name = "API Reference"
    url  = "/api/"
    pre = "fa fa-code fa-lg"
    weight = 20

[[menu.main]]
    name = "Tools"
    url  = "/tools/"
    pre = "fa fa-wrench fa-lg"
    weight = 50
